Repository CAU-MobileAppDev-2024-Team22/DailyCS, pull requests merged in 2024-12, with the labels that each got.

#10 Firestore 채점기능 연동
  app/src/main/java/com/example/firebaseexample/MainActivity.kt
  app/src/main/java/com/example/firebaseexample/data/model/QuizViewModel.kt
  app/src/main/java/com/example/firebaseexample/data/repository/QuizRepository.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/LoginPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/MainPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/RegisterPage.kt
  app/src/main/java/com/example/firebaseexample/ui/theme/Theme.kt
  app/src/main/java/com/example/firebaseexample/ui/theme/Type.kt
  app/src/main/res/font/.DS_Store
Labels: :sparkles: feat

#16 Feat/quizpage back
  .idea/deploymentTargetSelector.xml
  .idea/modules/app/firebaseExample.app.iml
  app/src/main/java/com/example/firebaseexample/MainActivity.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/ErrorPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizListPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizPage.kt
  local.properties
Labels: :sparkles: feat

#23 PR - 오늘의 문제 기능 추가
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/firebaseexample/MainActivity.kt
  app/src/main/java/com/example/firebaseexample/data/model/QuizViewModel.kt
  app/src/main/java/com/example/firebaseexample/data/repository/QuizRepository.kt
  app/src/main/java/com/example/firebaseexample/ui/components/QuizCard.kt
  app/src/main/java/com/example/firebaseexample/ui/components/QuizListCard.kt
  app/src/main/java/com/example/firebaseexample/ui/components/QuizScreen.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/CategoryQuizPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/MainPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizListPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizResultPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/TodayQuizPage.kt
  app/src/main/java/com/example/firebaseexample/viewmodel/TodayQuizViewModel.kt
  local.properties
Labels: :sparkles: feat

#20 [feat] 결과 페이지 차트 추가
  app/build.gradle.kts
  app/src/main/java/com/example/firebaseexample/ui/components/CircularChart.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizResultPage.kt
  app/src/main/java/com/example/firebaseexample/ui/theme/Color.kt
  settings.gradle.kts
Labels: :art: Design

#27 [DESIGN] QuizListPage 디자인 수정
  .idea/deploymentTargetSelector_backup.xml
  .idea/deviceManager.xml
  app/src/main/java/com/example/firebaseexample/ui/pages/QuizListPage.kt
  app/src/main/java/com/example/firebaseexample/ui/theme/Color.kt
  app/src/main/java/com/example/firebaseexample/ui/theme/Type.kt
  local.properties
Labels: :art: Design

#42 오늘의 문제/복습 추천 문제 인덱스 정보 저장 이슈 해결
  .idea/modules/app/firebaseExample.app.iml
  app/src/main/java/com/example/firebaseexample/data/model/QuizViewModel.kt
  app/src/main/java/com/example/firebaseexample/data/repository/QuizRepository.kt
  app/src/main/java/com/example/firebaseexample/ui/components/QuizScreen.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/BrushupQuizPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/NicknamePage.kt
Labels: :bug: bug

#44 끝
  app/src/main/java/com/example/firebaseexample/MainActivity.kt
  app/src/main/java/com/example/firebaseexample/ui/components/BottomNavBar.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/LoginPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/MainPage.kt
  app/src/main/java/com/example/firebaseexample/ui/pages/RegisterPage.kt
Labels: :sparkles: feat
